on:
  push

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        project_path: "./../../"
        build_command: "go build ./cmd/calc"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
